### ISSUE TITLE
classitis

### ISSUE THREAD

**Issue by vasilisvg** [reauv/minor-css-to-the-rescue#1]
Er valt te discussiëren over het nut van zo veel enorm specifieke classes.

**Comment by robertvansteen** [comment]
True, het is op zich overkill voor zo'n enkele pagina. 

Maar met grote projecten ben ik gewend om [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) te gebruiken, en de uitgebreidere variant daarvan met [namespaces](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/). Normaal gesproken volg ik hem nog strikter door ook niet direct styling toe te passen op HTML elementen maar alleen classes. Dat heb ik nu al losgelaten, maar het houdt mij in ieder geval _sane_ als developer als ik met (middel)grote projecten werk.

**Comment by vasilisvg** [comment]
Voor grote projecten gebruikte ik altijd SMACSS. Maar laatst las ik dit artikel dat naast BEM ook gebruik maakt van de semantiek van de elementen, door ARIA te gebruiken om te stijlen. Echt heel mooi. http://www.ebaytechblog.com/2015/11/04/how-our-css-framework-helps-enforce-accessibility/

**Comment by robertvansteen** [comment]
Thanks, erg interessant artikel!
Vooral dit sprak mij wel aan:

> Our selector now ensures that a button will visually appear like a button only if it has first been described as a button. You can almost think of this as TDD (test-driven development). If the HTML does not pass our ‘test’, the visual style will not be applied.
