### ISSUE TITLE
Nette code, en …

### ISSUE THREAD

**Issue by vasilisvg** [reauv/minor-css-to-the-rescue#4]
… supertoffe dingen doe je. Een plezier om door je CSS te struinen. Hoe bevallen de gids?

**Comment by robertvansteen** [comment]
De grids? Wel goed, was op deze pagina nog niet een echte use case voor maar de mogelijkheden zijn wel erg uitgebreid. Denk dat ik nu wel aardig door heb waar flexbox beter in is en waar grids beter in zijn. Die twee gecombineerd geven ons wel erg veel mogelijkheden voor de toekomst :smile:
